name: Push Current Repositry/Workflow to External Repository

on:
  workflow_dispatch:
    inputs:
      target_branch:
        description: 'Target Branch'
        required: true
        default: 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          path: ${{ github.workspace }}
    
      - name: Remove Git Extra Headers [Small Fix]
        working-directory: ${{ github.workspace }}
        run: git config --unset-all http.https://github.com/.extraheader

      # Optional - Clean up files
      - name: Remove files
        working-directory: ${{ github.workspace }}
        run: |
          find . -type d -name '.git' -exec rm -rf {} +
          find . -type d -name '.github' -exec rm -rf {} +
          find . -type d -name '.idea' -exec rm -rf {} +
          find . -type d -name 'venv' -exec rm -rf {} +
          find . -type d -name '__pycache__' -exec rm -rf {} +
          find . -name '.DS_Store' -exec rm -rf {} +
          find . -type d -name '.pytest_cache' -exec rm -rf {} +
          find . -type d -name '.DS_Store' -exec rm -rf {} + 

      - name: Pushes to another repository
        working-directory: ${{ github.workspace }}
        env:
          REPO_URL: ${{ secrets.EXTERNAL_REPO_URL }}
          USERNAME: ${{ secrets.EXTERNAL_REPO_USERNAME }}
          PASSWORD: ${{ secrets.EXTERNAL_REPO_PASSWORD }}
          EMAIL: ${{ secrets.EXTERNAL_REPO_EMAIL }}
          TARGET_BRANCH: ${{ github.event.inputs.target_branch }}
        run: |
          CURRENT_BRANCH="${GITHUB_REF#refs/heads/}"
          COMMIT_SHA="${GITHUB_SHA}"
          git init
          git config user.name "$USERNAME"
          git config user.email "$EMAIL"
          git add .
          git diff --staged --quiet || git commit -m "Pushing changes from commit ${CURRENT_BRANCH}@${COMMIT_SHA}"
          git remote add external "$REPO_URL"
          git push external HEAD:$TARGET_BRANCH --force
