name: Push External to External Repository

on:
  workflow_dispatch:
    inputs:
      target_branch:
        description: 'Target Branch'
        required: true
        default: 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout external repository
        uses: actions/checkout@v4
        with:
          path: ${{ github.workspace }}
          repository: ${{ secrets.EXTERNAL_REPOSITORY_URL }}
          # If the repo is private, pass your credentials as secrets.
          # Otherwise, comment out the 'username' and 'password' parameters
          # If no secret is specified, it will use your GitHub username
          username: ${{ secrets.EXTERNAL_USERNAME || github.actor }}
          # If your external repository uses needs a login
          password: ${{ secrets.EXTERNAL_ACCESS_TOKEN_OR_PASSWORD }}

      - name: Run small fix
        working-directory: ${{ github.workspace }}
        run: git config --unset-all http.https://github.com/.extraheader

      - name: Remove files
        working-directory: ${{ github.workspace }}
        run: |
          find . -type d -name '.git' -exec rm -rf {} +
          find . -type d -name '.github' -exec rm -rf {} +
          find . -type d -name '.idea' -exec rm -rf {} +
          find . -type d -name 'venv' -exec rm -rf {} +
          find . -type d -name '__pycache__' -exec rm -rf {} +
          find . -name '.DS_Store' -exec rm -rf {} +
          find . -type d -name '.pytest_cache' -exec rm -rf {} +
          find . -type d -name '.DS_Store' -exec rm -rf {} + 
      - name: Pushes to another repository
        env:
          REPO_URL: ${{ secrets.YOUR_SECRET_NAME_FOR_REPO_URL }}
          USERNAME: ${{ secrets.YOUR_SECRET_NAME_FOR_USERNAME }}
          PASSWORD: ${{ secrets.YOUR_SECRET_NAME_FOR_PASSWORD }}
          EMAIL: ${{ secrets.YOUR_SECRET_NAME_FOR_EMAIL }}
          TARGET_BRANCH: ${{ github.event.inputs.target_branch }}
        working-directory: ${{ github.workspace }}
        run: |
          CURRENT_BRANCH="${GITHUB_REF#refs/heads/}"
          COMMIT_SHA="${GITHUB_SHA}"
          git init
          git config user.name "$USERNAME"
          git config user.email "$EMAIL"
          git add .
          git diff --staged --quiet || git commit -m "Pushing changes from commit ${CURRENT_BRANCH}@${COMMIT_SHA}"
          git remote add external "$REPO_URL"
          git push external HEAD:$TARGET_BRANCH --force
