name: Miniconda Environment

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PYTHONUNBUFFERED: 1
      DEBIAN_FRONTEND: noninteractive
      CONDA_ENVIRONMENT_FILE: environment.yml
      CONDA_ENVIRONMENT_NAME: my_conda_environment
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        path: ${{ github.workspace }}

    - name: Check if Environment file exists
      run: |
        [ -f ${{ github.workspace }}/${{ env.CONDA_ENVIRONMENT_FILE }} ] || { echo "Error: ${{ env.CONDA_ENVIRONMENT_FILE }} file does not exist" >&2; exit 1; }

    - name: Install Miniconda
      run: |
        apt-get update && apt-get install -y wget
        mkdir -p ~/miniconda3
        wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda3/miniconda.sh
        bash ~/miniconda3/miniconda.sh -b -u -p ~/miniconda3
        rm ~/miniconda3/miniconda.sh

    - name: Create Conda Environment
      run: |
        echo "source ~/miniconda3/etc/profile.d/conda.sh" >> $GITHUB_PATH
        source ~/miniconda3/etc/profile.d/conda.sh
        conda env create --file ${{ github.workspace }}/{{ env.CONDA_ENVIRONMENT_FILE }}

    - name: Create a Python File For Testing
      working-directory: ${{ github.workspace }}
      run: |
        echo "print('Hello World!')" > myscript.py

    - name: Run Python Script
      working-directory: ${{ github.workspace }}
      run: |
        source ~/miniconda3/etc/profile.d/conda.sh
        conda activate {{ env.CONDA_ENVIRONMENT_NAME }}
        python myscript.py

    - name: Upload Repository [without cache files]
      working-directory: ${{ github.workspace }}
      run: |
          find . -type d -name '.git' -exec rm -rf {} +
          find . -type d -name '.github' -exec rm -rf {} +
          find . -type d -name '.idea' -exec rm -rf {} +
          find . -type d -name 'venv' -exec rm -rf {} +
          find . -type d -name '__pycache__' -exec rm -rf {} +
          sudo rm -rf ./{{ env.CONDA_ENVIRONMENT_FILE }}
          find . -name '.DS_Store' -exec rm -rf {} +
          find . -type d -name 'venv' -exec rm -rf {} +
          find . -type d -name '.pytest_cache' -exec rm -rf {} +   
          find . -type d -name '.DS_Store' -exec rm -rf {} + 
          zip -r ${{ runner.temp }}/workspace-${{ github.sha }}.zip .
    - uses: actions/upload-artifact@v4
      with:
        name: workspace-${{ github.sha }}
        path: ${{ runner.temp }}/workspace-${{ github.sha }}.zip
        retention-days: 7
        if-no-files-found: 'warn' #Default
        compression-level: 6 #Default
