name: Deploy Cloudflare Worker

on:
    workflow_dispatch:
      inputs:
        target_branch:
          description: 'Target Branch'
          required: true
          default: 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        path: ${{ github.workspace }}

    - uses: actions/setup-node@v4
      with:
        node-version: '16'

    - name: Install Cloudflare Wrangler
      working-directory: ${{ github.workspace }}
      run: |
        npm install -g wrangler
        # Or if you are using yarn
        # yarn global add wrangler

        # Install all of your project's packages
        npm install
        # Or if you are using yarn
        # yarn install

    - name: Publish Cloudflare Worker
      working-directory: ${{ github.workspace }}
      env:
        CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
      run: |
        wrangler deploy
