name: Push To DockerHub
on:
    workflow_dispatch:
        inputs:
          target_branch:
            description: 'Target Branch'
            required: true
            default: 'main'

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USER || github.actor }}
  REPOSITORY_NAME: ${{ github.repository || 'YOUR_REPOSITORY_NAME_HERE' }}
  DOCKERFILE_PATH: /

jobs:
  docker:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build and push image to DockerHub
        uses: docker/build-push-action@v3
        with:
          # Choose more OS's if you wish but these are the most used
          platforms: linux/amd64,linux/arm64
          file: ${{ github.workspace }}/Dockerfile
          push: true
          tags: ${{ env.DOCKERHUB_USERNAME }}/${{ env.REPOSITORY_NAME }}:latest
      
      - name: Update DockerHub Repository Description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
          repository: ${{ env.DOCKERHUB_USERNAME }}/${{ env.REPOSITORY_NAME }}
          readme-filepath: ./README.md